language: rust

sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libssh2-1-dev

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - cargo install cargo-kcov --force
  - cargo kcov --print-install-kcov-sh | $SHELL

script:
  - cargo test --no-run
  - cargo kcov --all --no-clean-rebuild --coveralls -v

cache:
  cargo: true
